### ISSUE TITLE
Help with Release

### ISSUE THREAD

**Issue by itsMikeLowrey** [bitcoinjs/bip174#1]
hi,
I just noticed that bip174 is scheduled for release sometime in September. Do you need help writing out this library? I would love to help if possible.

**Comment by dcousens** [comment]
> Do you need help writing out this library? I would love to help if possible.

Yes!
Test fixtures are appreciated.

**Comment by itsMikeLowrey** [comment]
Is there documentation for creating fixtures? I am currently just looking at fixtures from the bitcoinjs library, which should work.

**Comment by dcousens** [comment]
@itsMikeLowrey fixtures like in the bitcoinjs library would be _amazing_.

**Comment by prahaladbelavadi** [comment]
Ref:
- https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/fixtures/transaction_builder.json
- https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki

**Comment by junderw** [comment]
There was an implementation made by @alexbosworth and I got it working over at the PR #2 here.

As far as tests go, fixtures are inline JS which is meh.

**Comment by junderw** [comment]
Merged in #4 and released as v0.0.2 an initial implementation is available.
