### ISSUE TITLE
Taproot Leaf Script  - more than one entry

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bip174#30]
I have a question about the `Taproot Leaf Script` from [BIP371](https://github.com/bitcoin/bips/blob/master/bip-0371.mediawiki):

Taproot Leaf Script | PSBT_IN_TAP_LEAF_SCRIPT = 0x15 | <control block> | The control block for this leaf as specified in BIP 341. The control block contains the merkle tree path to this leaf. | <script> <8-bit uint> | The script for this leaf as would be provided in the witness stack  followed by the single byte leaf version. Note that the leaves included  in this field should be those that the signers of this input are  expected to be able to sign for. Finalizers should remove this field  after PSBT_IN_FINAL_SCRIPTWITNESS is constructed. Finalizers should remove this field after PSBT_IN_FINAL_SCRIPTWITNESS is constructed.
-- | -- | -- | -- | -- | --

In this libs  the filed is defined as a list: `tapLeafScript?: TapLeafScript[];`
However, when spending a taproot UTXO via script-path, only one `leaf` will be chosen. 
I don't see a scenario where two or more `tapLeafScript` can be used, am I missing something? How would the finalizer know which one to choose?

Related to: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742#issuecomment-1117577201

cc: @brandonblack

**Comment by brandonblack** [comment]
I believe the idea is that there may be several possible script paths that
the user is interested in collecting signatures for. The signer should
provide signatures for all that it can. The finalizer can throw an error if
multiple end up fully signed, or pick one at random to put in the tx, or
possibly other choices.

**Comment by motorina0** [comment]
> ...warts and all

The spec does not say explicitly that `PSBT_IN_TAP_LEAF_SCRIPT` is a multi-value field.
However, since the `<keydata>` is not `NONE` I guess we have to assume multiple values. So the current implementation is correct.

> ...or possibly other choices.

hmm, I don't like unpredictability :)
probably I will start with allowing just one (for simplicity), and relax it later (backwards compatible)

**Comment by brandonblack** [comment]
Yeah, the change from "there's one script that must be satisfied to spend this coin" to "there are 102938098123 possible scripts and a keypath that you must satisfy one of" really breaks the paradigm for a lot of software.

**Comment by tiero** [comment]
@motorina0 I agree that seems inconsistent: it seems to allow to set all possible script leaves, but for signature `PSBT_IN_TAP_SCRIPT_SIG` indeed wants a single value, if I am reading the bip right 🤔 

I agreed on throwing error if multiple script path are passed 


cc/ @louisinger

**Comment by louisinger** [comment]
> @motorina0 I agree that seems inconsistent: it seems to allow to set all possible script leaves, but for signature `PSBT_IN_TAP_SCRIPT_SIG` indeed wants a single value, if I am reading the bip right thinking

I think the idea behind "multiple `tapLeafScript`" is mainly to be able to share several branches of your script tree via PSBT. I could add two leaves on my input, send you the psbt, and let u choose how the spend the coin.

PS: from my understanding PSBT_IN_TAP_SCRIPT_SIG needs three data:
* the leafHash to identity which leaf the signature is associated to (and then get the controlBlock from tapLeafScript)
* the public key associated with the sig
* the signature

so theorically u could have several PSBT_IN_TAP_SCRIPT_SIG for the same leaf (in case of multisig for instance).

**Comment by junderw** [comment]
2-of-3 would be implemented as 3 branches of 2-of-2 with all combinations.

I would want to include both leaves where I am a participant.

**Comment by motorina0** [comment]
FYI: I've updated the `bitcoinjs-lib` PR to use the taproot input fields (see [comment](https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742#issuecomment-1132783983))

Regarding the finalizer:
- `finalzieInput()`:
  - if `tapKeySig` is found then it will finalize using key-spend
  - alternatively it will search for the closest `tapLeaf` that has a signature. Closest means shortest path in the control block
- `finalizeTaprootInput()`
  - this is a new public method. It allows specifying a `tapLeafHash`
  - if the `tapLeafHash` is provided, then it will try to finalize using that leaf
