### ISSUE TITLE
The base64 serialization of a psbt with no inputs or outputs cannot be parsed by Bitcoin Core

### ISSUE THREAD

**Issue by Randy808** [bitcoinjs/bip174#31]
Bitcoin core fails with the message ['TX decode failed extra data after PSBT'](https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/psbt.cpp#L474) when trying to parse a psbt with no inputs or outputs. This is because Bitcoin Core expects the input and output maps to exclude the separator when those sections do not contain any data.

**Comment by junderw** [comment]
According to BIP174:

https://github.com/bitcoin/bips/blob/ebea569f193577af8be51a48f0838fab38add0a9/bip-0174.mediawiki#user-content-Specification

```
 <psbt> := <magic> <global-map> <input-map>* <output-map>*
 <magic> := 0x70 0x73 0x62 0x74 0xFF
 <global-map> := <keypair>* 0x00
 <input-map> := <keypair>* 0x00
 <output-map> := <keypair>* 0x00
 <keypair> := <key> <value>
 <key> := <keylen> <keytype> <keydata>
 <value> := <valuelen> <valuedata>
```

If you have 0x00, 0x00 after the global-map, it should be interpreted as "1 input-map with 0 keypairs" and "1 output-map with 0 keypairs"...

This sounds like:

1. Bug/lack of clarity in BIP
2. Bug in Bitcoin Core

Please re-open if the BIP is changed.

**Comment by junderw** [comment]
(For more context: If my memory serves me correctly, the original BIP made it sound like `<psbt> := <magic> <global-map> <input-map> <output-map>` and the input/output maps were not optional, but the keypairs was "0-or-more" which is why the output is created in this way.)

**Comment by Randy808** [comment]
Have you tried running “bitcoin-cli  decodepsbt” with a base64 psbt that has no inputs or outputs? The test I added uses data from the BIP. I don’t see the problem you have with this issue, doesn’t the BIP explicitly allow the omission of the separator (hence the asterisk after input-map and output-map)?

**Comment by junderw** [comment]
Does decoding to accept any valid format?

Does encoding output a valid format?

If the answer to both of these questions is yes, there is no issue, but rather a feature request. ("Please output in this other valid format")

If the answer to either of those is no, please explain in detail why.

It was my understanding that the answer to both is yes.

If the issue is a feature request, I am leaning towards a no, but I'll think about it.

Thanks.
