### ISSUE TITLE
Roadmap Inquiry: Implementation Plans for PSBT Input Types of Hash and Time locks

### ISSUE THREAD

**Issue by saravanan7mani** [bitcoinjs/bip174#35]
Are there any plans on the roadmap to introduce the following input types:

Hash locks - PSBT_IN_RIPEMD160, PSBT_IN_SHA256, PSBT_IN_HASH160, and PSBT_IN_HASH256
Time locks - PSBT_IN_REQUIRED_TIME_LOCKTIME and PSBT_IN_REQUIRED_HEIGHT_LOCKTIME

**Comment by brandonblack** [comment]
As PSBTs are getting used more and more for working with HTLCs and other contracts this seems like it would come in quite handy.

**Comment by junderw** [comment]
To answer your question: There is no roadmap.

If you'd like to add something, propose a feature request or create a PR.

However, seeing as this library is called BIP174, I will reject any proposal that isn't in BIP174 or a related BIP that extends BIP174.

There's also some tricky decisions surrounding separation of concerns. This library tries to be strictly an encoding/decoding library, and the "Bitcoin coupled parts" are all implemented in bitcoinjs-lib's Psbt class.

However, more and more it seems like BIP174 related BIPs are trying to include Bitcoin concerns inside an encoding/decoding standard... (See: The whole Transaction abstraction we use is placed there to prevent needing to include a full Bitcoin Transaction parser, boiling it down into an interface that provides the minimum of required information through its methods.)

**Comment by junderw** [comment]
To clarify: I will add whatever I feel like whenever I feel like, and my current personal projects and day job do not require those things you mentioned, so if you're waiting on me it will be a while (if ever).

If you need them, feel free to make a PR if they are standardized.

**Comment by saravanan7mani** [comment]
Noted.

Those input types are part of BIP174. I updated the question.
