### ISSUE TITLE
Should change leafHashes as an option params of TapBip32Derivation?

### ISSUE THREAD

**Issue by chendatony31** [bitcoinjs/bip174#37]
Is `leafHashes` a required parameter for TapBip32Derivation? If I'm using the key spend script.

https://github.com/bitcoinjs/bip174/blob/master/src/lib/interfaces.d.ts#L98

**Comment by junderw** [comment]
Yes. The array should be empty.

**Comment by chendatony31** [comment]
Using empty array can not pass the check here: https://github.com/bitcoinjs/bip174/blob/master/src/lib/converter/shared/tapBip32Derivation.js#L36

**Comment by junderw** [comment]
Show me the error.

**Comment by chendatony31** [comment]
It's ok now. Thanks.  It seems to be an error with other parameters.
